
SEED: 42
SAVE_TEST_PREDS: False
DEBUG: True

DIRS:
    # Path to the directory containing the datalist in MSD json format
    DATASET: /home/GRAMES.POLYMTL.CA/u114716/tum-poly/datalists
    # Path to the directory for saving models
    SAVE_PATH: /home/GRAMES.POLYMTL.CA/u114716/tum-poly/saved_models  
    # Path to the directory for saving model predictions
    RESULTS_DIR: /home/GRAMES.POLYMTL.CA/u114716/tum-poly/results

DATA:
    NUM_SAMPLES_PER_IMAGE: 1

# Model parameters
MODEL:
    # nnunet model
    TYPE: nnunet
    INIT_FILTERS: 32
    IN_CHANNELS: 1
    NUM_CLASSES: 3
    ENABLE_DEEP_SUPERVISION: True
    PATCH_SIZE: [160, 128, 112]

# Optimizer parameters
OPTIM:
    OPTIMIZER: 'sgd'
    LR: 0.01
    WEIGHT_DECAY: 3e-5
    MAX_EPOCHS: 1
    VAL_EVERY_N_EPOCHS: 1
    PATIENCE: 20
    BATCH_SIZE: 2

# WandB params
WANDB:
    GRP_NAME: 'monai_nnunet'